language: generic

sudo: required
services:
        - docker
        

before_install:
        - docker build -t andrew/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true andrew/docker-reactnpm run test
